services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: mysql://root:XXXperu2020XXX.@ayala_back:3306/ayala2025
      NODE_ENV: ${NODE_ENV:-production}
      FRONTEND_URL: ${FRONTEND_URL}
      PORT: ${PORT:-3001}
    networks:
      - shared_network
    privileged: true

networks:
  shared_network:
    external: true
