import { Decimal } from '@prisma/client/runtime/library';

export interface IFactura {
  id_factura: number;
  estado_factura?: string | null;
  operacion: string;
  tipo_de_comprobante: number;
  serie: string;
  numero: number;
  sunat_transaction: number;
  id_proveedor: number;
  cliente_tipo_documento: number;
  cliente_numero_documento: string;
  cliente_denominacion: string;
  cliente_direccion?: string | null;
  cliente_email?: string | null;
  cliente_email_1?: string | null;
  cliente_email_2?: string | null;
  fecha_emision: Date;
  fecha_vencimiento?: Date | null;
  fecha_servicio?: Date | null;
  tipo_venta?: string | null;
  plazo_credito?: number | null;
  moneda: number;
  tipo_cambio?: Decimal | null;
  porcentaje_igv: Decimal;
  descuento_global?: Decimal | null;
  total_descuento?: Decimal | null;
  total_anticipo?: Decimal | null;
  total_gravada?: Decimal | null;
  total_inafecta?: Decimal | null;
  total_exonerada?: Decimal | null;
  total_igv?: Decimal | null;
  total_gratuita?: Decimal | null;
  total_otros_cargos?: Decimal | null;
  total_isc?: Decimal | null;
  total: Decimal;
  aplicar_detraccion: boolean;
  detraccion_tipo?: number | null;
  detraccion_porcentaje?: Decimal | null;
  detraccion_total?: Decimal | null;
  medio_pago_detraccion?: number | null;
  ubigeo_origen?: string | null;
  direccion_origen?: string | null;
  ubigeo_destino?: string | null;
  direccion_destino?: string | null;
  detalle_viaje?: string | null;
  percepcion_tipo?: number | null;
  percepcion_base_imponible?: Decimal | null;
  total_percepcion?: Decimal | null;
  total_incluido_percepcion?: Decimal | null;
  retencion_tipo?: number | null;
  retencion_base_imponible?: Decimal | null;
  total_retencion?: Decimal | null;
  fondo_garantia: boolean;
  fondo_garantia_valor?: string | null;
  orden_compra: boolean;
  orden_compra_valor?: string | null;
  placa_vehiculo?: string | null;
  orden_compra_servicio?: string | null;
  centro_costo_nivel1_codigo?: string | null;
  centro_costo_nivel2_codigo?: string | null;
  centro_costo_nivel3_codigo?: string | null;
  unidad?: string | null;
  unidad_id?: number | null;
  observaciones?: string | null;
  enviar_automaticamente_sunat: boolean;
  enviar_automaticamente_cliente: boolean;
  formato_pdf?: string | null;
  enlace?: string | null;
  enlace_del_pdf?: string | null;
  enlace_del_xml?: string | null;
  enlace_del_cdr?: string | null;
  cadena_para_codigo_qr?: string | null;
  codigo_hash?: string | null;
  aceptada_por_sunat?: boolean | null;
  sunat_description?: string | null;
  sunat_note?: string | null;
  sunat_responsecode?: string | null;
  sunat_soap_error?: string | null;
  created_at: Date;
  updated_at: Date;
}
