services:
  db:
    image: postgres:17
    container_name: ayala_postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: ayala_01
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: XXXperu2020XXX.
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared_network

  pgbouncer:
    image: pgbouncer/pgbouncer:latest
    container_name: ayala_pgbouncer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '5432:6432'
    environment:
      DATABASES_HOST: db
      DATABASES_PORT: 5432
      DATABASES_USER: nestuser
      DATABASES_PASSWORD: XXXperu2020XXX.
      DATABASES_DBNAME: ayala_01
      POOL_MODE: transaction
      PGBOUNCER_SERVER_RESET_QUERY: 'DISCARD ALL'
      PGBOUNCER_IGNORE_STARTUP_PARAMETERS: 'extra_float_digits'
      PGBOUNCER_MAX_CLIENT_CONN: '200'
      PGBOUNCER_DEFAULT_POOL_SIZE: '30'
      PGBOUNCER_MIN_POOL_SIZE: '10'
      PGBOUNCER_RESERVE_POOL_SIZE: '5'
      PGBOUNCER_SERVER_IDLE_TIMEOUT: '300'
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  postgres_data:
    # Volumen manejado por Docker, sin configuración adicional
